[package]
name = "textwrap-upgrade-diff"
version = "0.1.0"
edition = "2021"

[dependencies]
textwrap = "0.16.1"
textwrap_11 = {package="textwrap", version="0.11.0"}

[dev-dependencies]
pretty_assertions = "1.4.0"
